build:
	gcc -o main main.c header1.c -std=c99 -Wall -Wextra -Wunused -g

run:
	./main

clean:
	rm -f main

# sau gcc -o main main.c header2.c -std=c99 -Wall -Wextra -Wunused -g daca este cu al doilea header

